# Generated by Django 2.2.5 on 2019-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0002_auto_20190925_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authororder', models.IntegerField()),
                ('affiliation', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'unique_together': {('name', 'authororder', 'affiliation')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pmid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('journal', models.CharField(max_length=20)),
                ('pubdate', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('doi', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=20)),
                ('authors', models.ManyToManyField(to='Article.Author')),
            ],
        ),
    ]
