# Generated by Django 2.2.5 on 2019-09-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_article_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set(),
        ),
    ]
