# Generated by Django 2.2.5 on 2019-09-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20190925_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
