# Generated by Django 2.2.5 on 2019-10-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0010_auto_20190928_2112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='firstauthor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='firstauthor',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='FirstAuthor',
        ),
    ]
