# Generated by Django 2.2.5 on 2019-10-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0014_auto_20191004_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='firstauthor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='firstauthor',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='FirstAuthor',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
