# Generated by Django 2.2.5 on 2019-10-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0016_auto_20191007_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='author_article',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='author_article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='author_article',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Author_Article',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
