# Generated by Django 2.2.5 on 2019-10-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0018_auto_20191009_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_article',
            name='pubdate',
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='chinese',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ifactor',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
