# Generated by Django 2.2.5 on 2019-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0019_auto_20191009_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubdate',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='author_article',
            name='cofirst',
            field=models.CharField(db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='author_article',
            name='first',
            field=models.CharField(db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ifactor',
            field=models.FloatField(),
        ),
    ]
