# Generated by Django 2.2.6 on 2019-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0020_auto_20191009_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.TextField(null=True),
        ),
    ]
